/**
 * Discriminant Analysis classifiers.
 *
 * Implements Linear Discriminant Analysis (LDA) and Quadratic Discriminant Analysis (QDA).
 *
 * LDA projects data to a lower-dimensional space while maximizing class separability,
 * and can also be used as a classifier. QDA fits a separate covariance matrix per class,
 * allowing for non-linear decision boundaries.
 *
 * @see {@link https://deepbox.dev/docs/ml-advanced | Deepbox Discriminant Analysis}
 */

import { DataValidationError, InvalidParameterError, NotFittedError, ShapeError } from "../core";
import { type Tensor, tensor } from "../ndarray";
import { assertContiguous, validateFitInputs, validatePredictInputs } from "./_validation";
import type { Classifier, Transformer } from "./base";

// ---- Shared matrix helpers ----

function invertSymmetricMatrix(A: Float64Array, n: number): Float64Array {
  const w = 2 * n;
  const aug = new Float64Array(n * w);
  for (let i = 0; i < n; i++) {
    for (let j = 0; j < n; j++) {
      aug[i * w + j] = A[i * n + j] ?? 0;
    }
    aug[i * w + n + i] = 1;
  }

  for (let col = 0; col < n; col++) {
    let maxVal = Math.abs(aug[col * w + col] ?? 0);
    let maxRow = col;
    for (let row = col + 1; row < n; row++) {
      const val = Math.abs(aug[row * w + col] ?? 0);
      if (val > maxVal) {
        maxVal = val;
        maxRow = row;
      }
    }
    if (maxRow !== col) {
      for (let j = 0; j < w; j++) {
        const tmp = aug[col * w + j] ?? 0;
        aug[col * w + j] = aug[maxRow * w + j] ?? 0;
        aug[maxRow * w + j] = tmp;
      }
    }

    const pivot = aug[col * w + col] ?? 0;
    if (Math.abs(pivot) < 1e-15) {
      aug[col * w + col] = 1e-10;
    }
    const pivotInv = 1 / (aug[col * w + col] ?? 1e-10);
    for (let j = 0; j < w; j++) {
      aug[col * w + j] = (aug[col * w + j] ?? 0) * pivotInv;
    }

    for (let row = 0; row < n; row++) {
      if (row === col) continue;
      const factor = aug[row * w + col] ?? 0;
      for (let j = 0; j < w; j++) {
        aug[row * w + j] = (aug[row * w + j] ?? 0) - factor * (aug[col * w + j] ?? 0);
      }
    }
  }

  const inv = new Float64Array(n * n);
  for (let i = 0; i < n; i++) {
    for (let j = 0; j < n; j++) {
      inv[i * n + j] = aug[i * w + n + j] ?? 0;
    }
  }
  return inv;
}

function computeLogDeterminant(A: Float64Array, n: number): number {
  const L = new Float64Array(n * n);
  L.set(A);
  let logDet = 0;

  for (let col = 0; col < n; col++) {
    let maxVal = Math.abs(L[col * n + col] ?? 0);
    let maxRow = col;
    for (let row = col + 1; row < n; row++) {
      const val = Math.abs(L[row * n + col] ?? 0);
      if (val > maxVal) {
        maxVal = val;
        maxRow = row;
      }
    }
    if (maxRow !== col) {
      for (let j = 0; j < n; j++) {
        const tmp = L[col * n + j] ?? 0;
        L[col * n + j] = L[maxRow * n + j] ?? 0;
        L[maxRow * n + j] = tmp;
      }
    }

    const pivot = L[col * n + col] ?? 0;
    if (Math.abs(pivot) < 1e-300) {
      return -Infinity;
    }
    logDet += Math.log(Math.abs(pivot));

    for (let row = col + 1; row < n; row++) {
      const factor = (L[row * n + col] ?? 0) / pivot;
      for (let j = col; j < n; j++) {
        L[row * n + j] = (L[row * n + j] ?? 0) - factor * (L[col * n + j] ?? 0);
      }
    }
  }

  return logDet;
}

/**
 * Linear Discriminant Analysis (LDA).
 *
 * A classifier with a linear decision boundary, generated by fitting class
 * conditional densities to the data and using Bayes' rule. The model fits
 * a Gaussian density to each class, assuming all classes share the same
 * covariance matrix.
 *
 * Can also be used for supervised dimensionality reduction by projecting
 * data to the most discriminant directions.
 *
 * **Algorithm**:
 * 1. Compute class means and pooled within-class covariance
 * 2. Solve the generalized eigenvalue problem for discriminant directions
 * 3. Classify using log-posterior with shared covariance
 *
 * @example
 * ```ts
 * import { LinearDiscriminantAnalysis } from 'deepbox/ml';
 * import { tensor } from 'deepbox/ndarray';
 *
 * const X = tensor([[1, 2], [3, 4], [5, 6], [7, 8]]);
 * const y = tensor([0, 0, 1, 1]);
 *
 * const lda = new LinearDiscriminantAnalysis();
 * lda.fit(X, y);
 * const predictions = lda.predict(tensor([[2, 3], [6, 7]]));
 * ```
 */
export class LinearDiscriminantAnalysis implements Classifier, Transformer {
  private nComponents: number | undefined;
  private shrinkage: number | "auto" | undefined;
  private priors: readonly number[] | undefined;

  private classes_?: number[];
  private means_?: Float64Array[];
  private overallMean_?: Float64Array;
  private covInv_?: Float64Array;
  private logDet_?: number;
  private priors_?: Float64Array;
  private scalings_?: Float64Array;
  private nFeaturesIn_?: number;
  private nComponentsActual_?: number;
  private explainedVarianceRatio_?: Float64Array;
  private fitted = false;

  /**
   * @param options.nComponents - Number of components for dimensionality reduction (default: min(n_classes - 1, n_features))
   * @param options.shrinkage - Shrinkage parameter for covariance estimation. "auto" uses Ledoit-Wolf, number in [0,1] blends with identity. (default: undefined = no shrinkage)
   * @param options.priors - Prior probabilities of classes. If not given, class proportions are used.
   */
  constructor(
    options: {
      readonly nComponents?: number;
      readonly shrinkage?: number | "auto";
      readonly priors?: readonly number[];
    } = {}
  ) {
    this.nComponents = options.nComponents;
    this.shrinkage = options.shrinkage;
    this.priors = options.priors;

    if (this.nComponents !== undefined) {
      if (!Number.isInteger(this.nComponents) || this.nComponents < 1) {
        throw new InvalidParameterError(
          "nComponents must be an integer >= 1",
          "nComponents",
          this.nComponents
        );
      }
    }
    if (this.shrinkage !== undefined && this.shrinkage !== "auto") {
      if (typeof this.shrinkage !== "number" || this.shrinkage < 0 || this.shrinkage > 1) {
        throw new InvalidParameterError(
          "shrinkage must be 'auto' or a number in [0, 1]",
          "shrinkage",
          this.shrinkage
        );
      }
    }
  }

  fit(X: Tensor, y: Tensor): this {
    validateFitInputs(X, y);
    const nSamples = X.shape[0] ?? 0;
    const nFeatures = X.shape[1] ?? 0;
    this.nFeaturesIn_ = nFeatures;

    // Extract classes
    const classSet = new Set<number>();
    for (let i = 0; i < nSamples; i++) {
      classSet.add(Number(y.data[y.offset + i] ?? 0));
    }
    this.classes_ = Array.from(classSet).sort((a, b) => a - b);
    const nClasses = this.classes_.length;

    if (nClasses < 2) {
      throw new DataValidationError("LDA requires at least 2 classes");
    }

    // Determine nComponents
    const maxComponents = Math.min(nClasses - 1, nFeatures);
    const nComp = this.nComponents ?? maxComponents;
    if (nComp > maxComponents) {
      throw new InvalidParameterError(
        `nComponents=${nComp} must be <= min(n_classes - 1, n_features) = ${maxComponents}`,
        "nComponents",
        nComp
      );
    }
    this.nComponentsActual_ = nComp;

    // Build class index map
    const classIndex = new Map<number, number>();
    for (let c = 0; c < nClasses; c++) {
      classIndex.set(this.classes_[c] ?? 0, c);
    }

    // Compute class counts, means
    const classCounts = new Float64Array(nClasses);
    this.means_ = [];
    for (let c = 0; c < nClasses; c++) {
      this.means_.push(new Float64Array(nFeatures));
    }

    for (let i = 0; i < nSamples; i++) {
      const ci = classIndex.get(Number(y.data[y.offset + i] ?? 0)) ?? 0;
      classCounts[ci] = (classCounts[ci] ?? 0) + 1;
      const mean = this.means_[ci];
      if (mean) {
        for (let j = 0; j < nFeatures; j++) {
          mean[j] = (mean[j] ?? 0) + Number(X.data[X.offset + i * nFeatures + j] ?? 0);
        }
      }
    }

    for (let c = 0; c < nClasses; c++) {
      const mean = this.means_[c];
      const count = classCounts[c] ?? 1;
      if (mean) {
        for (let j = 0; j < nFeatures; j++) {
          mean[j] = (mean[j] ?? 0) / count;
        }
      }
    }

    // Overall mean
    this.overallMean_ = new Float64Array(nFeatures);
    for (let j = 0; j < nFeatures; j++) {
      let sum = 0;
      for (let i = 0; i < nSamples; i++) {
        sum += Number(X.data[X.offset + i * nFeatures + j] ?? 0);
      }
      this.overallMean_[j] = sum / nSamples;
    }

    // Priors
    this.priors_ = new Float64Array(nClasses);
    if (this.priors) {
      if (this.priors.length !== nClasses) {
        throw new InvalidParameterError(
          `priors must have length ${nClasses}; got ${this.priors.length}`,
          "priors",
          this.priors
        );
      }
      let sum = 0;
      for (let c = 0; c < nClasses; c++) {
        const p = this.priors[c] ?? 0;
        if (p < 0) {
          throw new InvalidParameterError("priors must be non-negative", "priors", this.priors);
        }
        this.priors_[c] = p;
        sum += p;
      }
      if (Math.abs(sum - 1) > 1e-6) {
        throw new InvalidParameterError("priors must sum to 1", "priors", this.priors);
      }
    } else {
      for (let c = 0; c < nClasses; c++) {
        this.priors_[c] = (classCounts[c] ?? 0) / nSamples;
      }
    }

    // Compute pooled within-class scatter matrix Sw
    const Sw = new Float64Array(nFeatures * nFeatures);
    for (let i = 0; i < nSamples; i++) {
      const ci = classIndex.get(Number(y.data[y.offset + i] ?? 0)) ?? 0;
      const mean = this.means_[ci];
      if (!mean) continue;
      for (let p = 0; p < nFeatures; p++) {
        const dp = Number(X.data[X.offset + i * nFeatures + p] ?? 0) - (mean[p] ?? 0);
        for (let q = p; q < nFeatures; q++) {
          const dq = Number(X.data[X.offset + i * nFeatures + q] ?? 0) - (mean[q] ?? 0);
          Sw[p * nFeatures + q] = (Sw[p * nFeatures + q] ?? 0) + dp * dq;
        }
      }
    }
    // Symmetrize
    for (let p = 0; p < nFeatures; p++) {
      for (let q = p + 1; q < nFeatures; q++) {
        Sw[q * nFeatures + p] = Sw[p * nFeatures + q] ?? 0;
      }
    }
    // Normalize
    const swDenom = Math.max(nSamples - nClasses, 1);
    for (let i = 0; i < nFeatures * nFeatures; i++) {
      Sw[i] = (Sw[i] ?? 0) / swDenom;
    }

    // Apply shrinkage if requested
    let shrinkageValue = 0;
    if (this.shrinkage === "auto") {
      shrinkageValue = ledoitWolfShrinkage(nFeatures, Sw);
    } else if (typeof this.shrinkage === "number") {
      shrinkageValue = this.shrinkage;
    }

    if (shrinkageValue > 0) {
      let trace = 0;
      for (let i = 0; i < nFeatures; i++) {
        trace += Sw[i * nFeatures + i] ?? 0;
      }
      const mu = trace / nFeatures;
      for (let i = 0; i < nFeatures * nFeatures; i++) {
        Sw[i] = (Sw[i] ?? 0) * (1 - shrinkageValue);
      }
      for (let i = 0; i < nFeatures; i++) {
        Sw[i * nFeatures + i] = (Sw[i * nFeatures + i] ?? 0) + shrinkageValue * mu;
      }
    }

    // Invert Sw for classification
    this.covInv_ = invertSymmetricMatrix(Sw, nFeatures);
    this.logDet_ = computeLogDeterminant(Sw, nFeatures);

    // Compute between-class scatter Sb for dimensionality reduction
    const Sb = new Float64Array(nFeatures * nFeatures);
    for (let c = 0; c < nClasses; c++) {
      const mean = this.means_[c];
      if (!mean) continue;
      const nc = classCounts[c] ?? 0;
      for (let p = 0; p < nFeatures; p++) {
        const dp = (mean[p] ?? 0) - (this.overallMean_[p] ?? 0);
        for (let q = 0; q < nFeatures; q++) {
          const dq = (mean[q] ?? 0) - (this.overallMean_[q] ?? 0);
          Sb[p * nFeatures + q] = (Sb[p * nFeatures + q] ?? 0) + nc * dp * dq;
        }
      }
    }

    // Solve Sw^{-1} Sb for eigenvalues (discriminant directions)
    const SwInvSb = new Float64Array(nFeatures * nFeatures);
    for (let i = 0; i < nFeatures; i++) {
      for (let j = 0; j < nFeatures; j++) {
        let sum = 0;
        for (let k = 0; k < nFeatures; k++) {
          sum += (this.covInv_[i * nFeatures + k] ?? 0) * (Sb[k * nFeatures + j] ?? 0);
        }
        SwInvSb[i * nFeatures + j] = sum;
      }
    }

    // Power iteration for top eigenvectors of SwInvSb
    const { vectors, values } = topEigenvectors(SwInvSb, nFeatures, nComp);
    this.scalings_ = vectors;

    // Explained variance ratio
    const totalEigSum = values.reduce((a, b) => a + b, 0);
    this.explainedVarianceRatio_ = new Float64Array(nComp);
    if (totalEigSum > 0) {
      for (let i = 0; i < nComp; i++) {
        this.explainedVarianceRatio_[i] = (values[i] ?? 0) / totalEigSum;
      }
    }

    this.fitted = true;
    return this;
  }

  predict(X: Tensor): Tensor {
    if (!this.fitted) {
      throw new NotFittedError("LinearDiscriminantAnalysis must be fitted before prediction");
    }
    const logPost = this.computeLogPosteriors(X);
    const nSamples = logPost.length;
    const predictions: number[] = [];

    for (let i = 0; i < nSamples; i++) {
      const row = logPost[i];
      if (!row) continue;
      let maxVal = -Infinity;
      let maxIdx = 0;
      for (let c = 0; c < row.length; c++) {
        if ((row[c] ?? -Infinity) > maxVal) {
          maxVal = row[c] ?? -Infinity;
          maxIdx = c;
        }
      }
      predictions.push(this.classes_?.[maxIdx] ?? 0);
    }

    return tensor(predictions, { dtype: "int32" });
  }

  predictProba(X: Tensor): Tensor {
    if (!this.fitted) {
      throw new NotFittedError("LinearDiscriminantAnalysis must be fitted before prediction");
    }
    const logPost = this.computeLogPosteriors(X);
    const probabilities: number[][] = [];

    for (const row of logPost) {
      const maxLP = Math.max(...row);
      const exps = row.map((lp) => Math.exp(lp - maxLP));
      const sumExps = exps.reduce((a, b) => a + b, 0);
      probabilities.push(exps.map((e) => e / sumExps));
    }

    return tensor(probabilities);
  }

  /**
   * Project data to the most discriminant directions.
   */
  transform(X: Tensor): Tensor {
    if (!this.fitted || !this.scalings_ || !this.overallMean_) {
      throw new NotFittedError("LinearDiscriminantAnalysis must be fitted before transform");
    }
    validatePredictInputs(X, this.nFeaturesIn_ ?? 0, "LinearDiscriminantAnalysis");

    const nSamples = X.shape[0] ?? 0;
    const nFeatures = X.shape[1] ?? 0;
    const nComp = this.nComponentsActual_ ?? 0;
    const result: number[][] = [];

    for (let i = 0; i < nSamples; i++) {
      const row: number[] = [];
      for (let k = 0; k < nComp; k++) {
        let sum = 0;
        for (let j = 0; j < nFeatures; j++) {
          const centered =
            Number(X.data[X.offset + i * nFeatures + j] ?? 0) - (this.overallMean_[j] ?? 0);
          sum += centered * (this.scalings_[j * nComp + k] ?? 0);
        }
        row.push(sum);
      }
      result.push(row);
    }

    return tensor(result);
  }

  fitTransform(X: Tensor, y?: Tensor): Tensor {
    if (!y) {
      throw new InvalidParameterError("LDA.fitTransform requires y (supervised)", "y", undefined);
    }
    this.fit(X, y);
    return this.transform(X);
  }

  score(X: Tensor, y: Tensor): number {
    if (y.ndim !== 1) {
      throw new ShapeError(`y must be 1-dimensional; got ndim=${y.ndim}`);
    }
    assertContiguous(y, "y");
    const yPred = this.predict(X);
    let correct = 0;
    for (let i = 0; i < y.size; i++) {
      if (Number(y.data[y.offset + i] ?? 0) === Number(yPred.data[yPred.offset + i] ?? 0)) {
        correct++;
      }
    }
    return correct / y.size;
  }

  get classes(): Tensor | undefined {
    if (!this.fitted || !this.classes_) return undefined;
    return tensor(this.classes_, { dtype: "int32" });
  }

  get explainedVarianceRatio(): Float64Array | undefined {
    return this.explainedVarianceRatio_;
  }

  getParams(): Record<string, unknown> {
    return {
      nComponents: this.nComponents,
      shrinkage: this.shrinkage,
      priors: this.priors,
    };
  }

  setParams(params: Record<string, unknown>): this {
    for (const [key, value] of Object.entries(params)) {
      switch (key) {
        case "nComponents":
          if (
            value !== undefined &&
            (typeof value !== "number" || !Number.isInteger(value) || value < 1)
          ) {
            throw new InvalidParameterError(
              "nComponents must be an integer >= 1",
              "nComponents",
              value
            );
          }
          this.nComponents = value as number | undefined;
          break;
        case "shrinkage":
          if (
            value !== undefined &&
            value !== "auto" &&
            (typeof value !== "number" || value < 0 || value > 1)
          ) {
            throw new InvalidParameterError(
              "shrinkage must be 'auto' or a number in [0,1]",
              "shrinkage",
              value
            );
          }
          this.shrinkage = value as number | "auto" | undefined;
          break;
        case "priors":
          this.priors = value as readonly number[] | undefined;
          break;
        default:
          throw new InvalidParameterError(`Unknown parameter: ${key}`, key, value);
      }
    }
    return this;
  }

  // ---- Private helpers ----

  private computeLogPosteriors(X: Tensor): number[][] {
    if (!this.covInv_ || !this.means_ || !this.priors_ || !this.classes_) {
      throw new NotFittedError("LinearDiscriminantAnalysis must be fitted");
    }
    validatePredictInputs(X, this.nFeaturesIn_ ?? 0, "LinearDiscriminantAnalysis");

    const nSamples = X.shape[0] ?? 0;
    const nFeatures = X.shape[1] ?? 0;
    const nClasses = this.classes_.length;
    const result: number[][] = [];

    for (let i = 0; i < nSamples; i++) {
      const logPosteriors: number[] = [];
      for (let c = 0; c < nClasses; c++) {
        const mean = this.means_[c];
        if (!mean) {
          logPosteriors.push(-Infinity);
          continue;
        }
        // Mahalanobis: (x - mu)^T Sigma^{-1} (x - mu)
        let mahal = 0;
        for (let p = 0; p < nFeatures; p++) {
          const dp = Number(X.data[X.offset + i * nFeatures + p] ?? 0) - (mean[p] ?? 0);
          for (let q = 0; q < nFeatures; q++) {
            const dq = Number(X.data[X.offset + i * nFeatures + q] ?? 0) - (mean[q] ?? 0);
            mahal += dp * (this.covInv_[p * nFeatures + q] ?? 0) * dq;
          }
        }
        const logPrior = Math.log(Math.max(this.priors_[c] ?? 1e-300, 1e-300));
        const logLik = -0.5 * (nFeatures * Math.log(2 * Math.PI) + (this.logDet_ ?? 0) + mahal);
        logPosteriors.push(logLik + logPrior);
      }
      result.push(logPosteriors);
    }

    return result;
  }
}

/**
 * Quadratic Discriminant Analysis (QDA).
 *
 * A classifier with a quadratic decision boundary, generated by fitting class
 * conditional densities to the data and using Bayes' rule. Unlike LDA, QDA fits
 * a separate covariance matrix per class, allowing for more flexible (non-linear)
 * decision boundaries.
 *
 * @example
 * ```ts
 * import { QuadraticDiscriminantAnalysis } from 'deepbox/ml';
 * import { tensor } from 'deepbox/ndarray';
 *
 * const X = tensor([[1, 2], [3, 4], [5, 6], [7, 8]]);
 * const y = tensor([0, 0, 1, 1]);
 *
 * const qda = new QuadraticDiscriminantAnalysis();
 * qda.fit(X, y);
 * const predictions = qda.predict(tensor([[2, 3], [6, 7]]));
 * ```
 */
export class QuadraticDiscriminantAnalysis implements Classifier {
  private regParam: number;
  private priors: readonly number[] | undefined;

  private classes_?: number[];
  private means_?: Float64Array[];
  private covInvs_?: Float64Array[];
  private logDets_?: number[];
  private priors_?: Float64Array;
  private nFeaturesIn_?: number;
  private fitted = false;

  /**
   * @param options.regParam - Regularization parameter added to diagonal of each class covariance (default: 0)
   * @param options.priors - Prior probabilities of classes
   */
  constructor(
    options: {
      readonly regParam?: number;
      readonly priors?: readonly number[];
    } = {}
  ) {
    this.regParam = options.regParam ?? 0;
    this.priors = options.priors;

    if (!Number.isFinite(this.regParam) || this.regParam < 0) {
      throw new InvalidParameterError(
        "regParam must be a finite number >= 0",
        "regParam",
        this.regParam
      );
    }
  }

  fit(X: Tensor, y: Tensor): this {
    validateFitInputs(X, y);
    const nSamples = X.shape[0] ?? 0;
    const nFeatures = X.shape[1] ?? 0;
    this.nFeaturesIn_ = nFeatures;

    // Extract classes
    const classSet = new Set<number>();
    for (let i = 0; i < nSamples; i++) {
      classSet.add(Number(y.data[y.offset + i] ?? 0));
    }
    this.classes_ = Array.from(classSet).sort((a, b) => a - b);
    const nClasses = this.classes_.length;

    if (nClasses < 2) {
      throw new DataValidationError("QDA requires at least 2 classes");
    }

    // Build class index map
    const classIndex = new Map<number, number>();
    for (let c = 0; c < nClasses; c++) {
      classIndex.set(this.classes_[c] ?? 0, c);
    }

    // Group samples by class
    const classIndices: number[][] = Array.from({ length: nClasses }, () => []);
    for (let i = 0; i < nSamples; i++) {
      const ci = classIndex.get(Number(y.data[y.offset + i] ?? 0)) ?? 0;
      classIndices[ci]?.push(i);
    }

    // Priors
    this.priors_ = new Float64Array(nClasses);
    if (this.priors) {
      if (this.priors.length !== nClasses) {
        throw new InvalidParameterError(
          `priors must have length ${nClasses}; got ${this.priors.length}`,
          "priors",
          this.priors
        );
      }
      let sum = 0;
      for (let c = 0; c < nClasses; c++) {
        const p = this.priors[c] ?? 0;
        if (p < 0) {
          throw new InvalidParameterError("priors must be non-negative", "priors", this.priors);
        }
        this.priors_[c] = p;
        sum += p;
      }
      if (Math.abs(sum - 1) > 1e-6) {
        throw new InvalidParameterError("priors must sum to 1", "priors", this.priors);
      }
    } else {
      for (let c = 0; c < nClasses; c++) {
        this.priors_[c] = (classIndices[c]?.length ?? 0) / nSamples;
      }
    }

    // Compute per-class means and covariances
    this.means_ = [];
    this.covInvs_ = [];
    this.logDets_ = [];

    for (let c = 0; c < nClasses; c++) {
      const indices = classIndices[c] ?? [];
      const nc = indices.length;

      // Class mean
      const mean = new Float64Array(nFeatures);
      for (const idx of indices) {
        for (let j = 0; j < nFeatures; j++) {
          mean[j] = (mean[j] ?? 0) + Number(X.data[X.offset + idx * nFeatures + j] ?? 0);
        }
      }
      for (let j = 0; j < nFeatures; j++) {
        mean[j] = (mean[j] ?? 0) / nc;
      }
      this.means_.push(mean);

      // Class covariance
      const cov = new Float64Array(nFeatures * nFeatures);
      for (const idx of indices) {
        for (let p = 0; p < nFeatures; p++) {
          const dp = Number(X.data[X.offset + idx * nFeatures + p] ?? 0) - (mean[p] ?? 0);
          for (let q = p; q < nFeatures; q++) {
            const dq = Number(X.data[X.offset + idx * nFeatures + q] ?? 0) - (mean[q] ?? 0);
            cov[p * nFeatures + q] = (cov[p * nFeatures + q] ?? 0) + dp * dq;
          }
        }
      }
      // Symmetrize and normalize
      const denom = Math.max(nc - 1, 1);
      for (let p = 0; p < nFeatures; p++) {
        for (let q = p; q < nFeatures; q++) {
          cov[p * nFeatures + q] = (cov[p * nFeatures + q] ?? 0) / denom;
          cov[q * nFeatures + p] = cov[p * nFeatures + q] ?? 0;
        }
      }

      // Add regularization
      if (this.regParam > 0) {
        for (let i = 0; i < nFeatures; i++) {
          cov[i * nFeatures + i] = (cov[i * nFeatures + i] ?? 0) + this.regParam;
        }
      }

      // Invert and compute log-determinant
      this.covInvs_.push(invertSymmetricMatrix(cov, nFeatures));
      this.logDets_.push(computeLogDeterminant(cov, nFeatures));
    }

    this.fitted = true;
    return this;
  }

  predict(X: Tensor): Tensor {
    if (!this.fitted) {
      throw new NotFittedError("QuadraticDiscriminantAnalysis must be fitted before prediction");
    }
    const logPost = this.computeLogPosteriors(X);
    const predictions: number[] = [];

    for (const row of logPost) {
      let maxVal = -Infinity;
      let maxIdx = 0;
      for (let c = 0; c < row.length; c++) {
        if ((row[c] ?? -Infinity) > maxVal) {
          maxVal = row[c] ?? -Infinity;
          maxIdx = c;
        }
      }
      predictions.push(this.classes_?.[maxIdx] ?? 0);
    }

    return tensor(predictions, { dtype: "int32" });
  }

  predictProba(X: Tensor): Tensor {
    if (!this.fitted) {
      throw new NotFittedError("QuadraticDiscriminantAnalysis must be fitted before prediction");
    }
    const logPost = this.computeLogPosteriors(X);
    const probabilities: number[][] = [];

    for (const row of logPost) {
      const maxLP = Math.max(...row);
      const exps = row.map((lp) => Math.exp(lp - maxLP));
      const sumExps = exps.reduce((a, b) => a + b, 0);
      probabilities.push(exps.map((e) => e / sumExps));
    }

    return tensor(probabilities);
  }

  score(X: Tensor, y: Tensor): number {
    if (y.ndim !== 1) {
      throw new ShapeError(`y must be 1-dimensional; got ndim=${y.ndim}`);
    }
    assertContiguous(y, "y");
    const yPred = this.predict(X);
    let correct = 0;
    for (let i = 0; i < y.size; i++) {
      if (Number(y.data[y.offset + i] ?? 0) === Number(yPred.data[yPred.offset + i] ?? 0)) {
        correct++;
      }
    }
    return correct / y.size;
  }

  get classes(): Tensor | undefined {
    if (!this.fitted || !this.classes_) return undefined;
    return tensor(this.classes_, { dtype: "int32" });
  }

  getParams(): Record<string, unknown> {
    return {
      regParam: this.regParam,
      priors: this.priors,
    };
  }

  setParams(params: Record<string, unknown>): this {
    for (const [key, value] of Object.entries(params)) {
      switch (key) {
        case "regParam":
          if (typeof value !== "number" || !Number.isFinite(value) || value < 0) {
            throw new InvalidParameterError(
              "regParam must be a finite number >= 0",
              "regParam",
              value
            );
          }
          this.regParam = value;
          break;
        case "priors":
          this.priors = value as readonly number[] | undefined;
          break;
        default:
          throw new InvalidParameterError(`Unknown parameter: ${key}`, key, value);
      }
    }
    return this;
  }

  // ---- Private helpers ----

  private computeLogPosteriors(X: Tensor): number[][] {
    if (!this.covInvs_ || !this.means_ || !this.priors_ || !this.logDets_ || !this.classes_) {
      throw new NotFittedError("QuadraticDiscriminantAnalysis must be fitted");
    }
    validatePredictInputs(X, this.nFeaturesIn_ ?? 0, "QuadraticDiscriminantAnalysis");

    const nSamples = X.shape[0] ?? 0;
    const nFeatures = X.shape[1] ?? 0;
    const nClasses = this.classes_.length;
    const result: number[][] = [];

    for (let i = 0; i < nSamples; i++) {
      const logPosteriors: number[] = [];
      for (let c = 0; c < nClasses; c++) {
        const mean = this.means_[c];
        const covInv = this.covInvs_[c];
        if (!mean || !covInv) {
          logPosteriors.push(-Infinity);
          continue;
        }
        let mahal = 0;
        for (let p = 0; p < nFeatures; p++) {
          const dp = Number(X.data[X.offset + i * nFeatures + p] ?? 0) - (mean[p] ?? 0);
          for (let q = 0; q < nFeatures; q++) {
            const dq = Number(X.data[X.offset + i * nFeatures + q] ?? 0) - (mean[q] ?? 0);
            mahal += dp * (covInv[p * nFeatures + q] ?? 0) * dq;
          }
        }
        const logPrior = Math.log(Math.max(this.priors_[c] ?? 1e-300, 1e-300));
        const logLik = -0.5 * (nFeatures * Math.log(2 * Math.PI) + (this.logDets_[c] ?? 0) + mahal);
        logPosteriors.push(logLik + logPrior);
      }
      result.push(logPosteriors);
    }

    return result;
  }
}

// ---- Module-level helpers ----

function ledoitWolfShrinkage(nFeatures: number, S: Float64Array): number {
  let trS = 0;
  let trS2 = 0;
  for (let i = 0; i < nFeatures; i++) {
    trS += S[i * nFeatures + i] ?? 0;
    for (let j = 0; j < nFeatures; j++) {
      const v = S[i * nFeatures + j] ?? 0;
      trS2 += v * v;
    }
  }

  const rhoNum = (1 - 2 / nFeatures) * trS2 + trS * trS;
  const rhoDen = (nFeatures + 1 - 2 / nFeatures) * (trS2 - (trS * trS) / nFeatures);

  if (Math.abs(rhoDen) < 1e-15) return 1;
  return Math.max(0, Math.min(1, rhoNum / rhoDen));
}

function topEigenvectors(
  M: Float64Array,
  n: number,
  k: number
): { vectors: Float64Array; values: number[] } {
  const vectors = new Float64Array(n * k);
  const values: number[] = [];
  const Mcopy = new Float64Array(M);

  for (let idx = 0; idx < k; idx++) {
    const v = new Float64Array(n);
    for (let i = 0; i < n; i++) {
      v[i] = (i === idx ? 1 : 0) + 0.01 * Math.sin(i * 7 + idx * 13);
    }

    let eigenvalue = 0;
    for (let iter = 0; iter < 300; iter++) {
      const Mv = new Float64Array(n);
      for (let i = 0; i < n; i++) {
        let sum = 0;
        for (let j = 0; j < n; j++) {
          sum += (Mcopy[i * n + j] ?? 0) * (v[j] ?? 0);
        }
        Mv[i] = sum;
      }

      let norm = 0;
      for (let i = 0; i < n; i++) {
        norm += (Mv[i] ?? 0) * (Mv[i] ?? 0);
      }
      norm = Math.sqrt(norm);
      if (norm < 1e-15) break;

      eigenvalue = norm;
      let dot = 0;
      for (let i = 0; i < n; i++) {
        dot += (Mv[i] ?? 0) * (v[i] ?? 0);
      }
      if (dot < 0) eigenvalue = -eigenvalue;

      for (let i = 0; i < n; i++) {
        v[i] = (Mv[i] ?? 0) / norm;
      }
    }

    values.push(Math.abs(eigenvalue));
    for (let i = 0; i < n; i++) {
      vectors[i * k + idx] = v[i] ?? 0;
    }

    // Deflate
    for (let i = 0; i < n; i++) {
      for (let j = 0; j < n; j++) {
        Mcopy[i * n + j] = (Mcopy[i * n + j] ?? 0) - eigenvalue * (v[i] ?? 0) * (v[j] ?? 0);
      }
    }
  }

  return { vectors, values };
}
